import { writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { pinyin } from 'pinyin-pro'
import { format, resolveConfig } from 'prettier'

import type { Joker } from '../src/data/types'
import { normalizeSearchText } from '../src/search/normalize'

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const generatedFile = join(projectRoot, 'src/search/joker-search.generated.ts')

export type GeneratedJokerSearchAliases = Readonly<
  Record<string, readonly [pinyin: string, initials: string]>
>

function pinyinText(value: string, initials: boolean): string {
  const result = pinyin(value, {
    type: 'array',
    toneType: 'none',
    nonZh: 'consecutive',
    ...(initials ? { pattern: 'first' as const } : {}),
  })

  return normalizeSearchText(result.join(''))
}

export function generateJokerSearchAliases(jokers: readonly Joker[]): GeneratedJokerSearchAliases {
  return Object.fromEntries(
    jokers.map((joker) => [
      joker.id,
      [pinyinText(joker.name.zhCN, false), pinyinText(joker.name.zhCN, true)] as const,
    ]),
  )
}

export async function writeJokerSearchAliases(jokers: readonly Joker[]): Promise<void> {
  const aliases = generateJokerSearchAliases(jokers)
  const source = `// Generated by scripts/generate-joker-search.ts. Do not edit by hand.\n\nexport const JOKER_SEARCH_ALIASES: Readonly<Record<string, readonly [pinyin: string, initials: string]>> = ${JSON.stringify(aliases, null, 2)}\n`
  const prettierConfig = (await resolveConfig(generatedFile)) ?? {}
  await writeFile(generatedFile, await format(source, { ...prettierConfig, parser: 'typescript' }))
  console.log(`[data] wrote search aliases for ${jokers.length} Jokers`)
}

if (import.meta.main) {
  const { jokers } = await import('../src/data/jokers.generated')
  await writeJokerSearchAliases(jokers)
}
