import { createHash } from 'node:crypto'
import { readFile, writeFile } from 'node:fs/promises'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

import { format, resolveConfig } from 'prettier'

import { JOKER_CLASSIFICATION_VERSION } from '../src/data/types'
import { createExpectedGeneratedArtifacts, type SourceReviewFile } from './check-generated-data'

const projectRoot = dirname(dirname(fileURLToPath(import.meta.url)))
const sourceReviewFile = join(projectRoot, 'data/upstream/jokers.wiki.generated.json')
const generatedFile = join(projectRoot, 'src/data/jokers.generated.ts')
const provenanceFile = join(projectRoot, 'data/jokers.provenance.generated.json')

async function main(): Promise<void> {
  const sourceReview = JSON.parse(await readFile(sourceReviewFile, 'utf8')) as SourceReviewFile &
    Record<string, unknown>
  const nextSourceReview = {
    ...sourceReview,
    metadata: {
      ...sourceReview.metadata,
      classificationVersion: JOKER_CLASSIFICATION_VERSION,
    },
  } satisfies SourceReviewFile & Record<string, unknown>

  const localImageSha1ById = Object.fromEntries(
    await Promise.all(
      nextSourceReview.jokers.map(async ({ id }) => [
        id,
        createHash('sha1')
          .update(await readFile(join(projectRoot, 'public/jokers', `${id}.png`)))
          .digest('hex'),
      ]),
    ),
  )
  const generated = createExpectedGeneratedArtifacts(nextSourceReview, localImageSha1ById)
  const source = `// Generated by scripts/regenerate-jokers.ts from the checked-in source review. Do not edit by hand.
import type { Joker, JokerDataMeta } from './types'

export const JOKER_DATA_META: JokerDataMeta = ${JSON.stringify(generated.metadata, null, 2)}

export const jokers: readonly Joker[] = ${JSON.stringify(generated.jokers, null, 2)}
`
  const prettierConfig = (await resolveConfig(generatedFile)) ?? {}

  await Promise.all([
    writeFile(generatedFile, await format(source, { ...prettierConfig, parser: 'typescript' })),
    writeFile(sourceReviewFile, `${JSON.stringify(nextSourceReview, null, 2)}\n`),
    writeFile(provenanceFile, `${JSON.stringify(generated.provenance, null, 2)}\n`),
  ])

  console.log(
    `[data] regenerated ${generated.jokers.length} Jokers at classification c${JOKER_CLASSIFICATION_VERSION}`,
  )
}

if (import.meta.main) await main()
